app/adresboek/urls.py
from django.urls import path
from . import views

# Register our App name
app_name = 'adresboek'


#Dynamic Pages Adressem
urlpatterns = [
    # ex /adressen
    path('', views.AdresListView.as_view(), name='adres_lijst'),
    path('adressen/toevoegen/', views.AdresCreate.as_view(), name='adres_toevoegen'),
    path('adressen/bewerken/<slug:slug>/', views.AdresUpdate.as_view(), name='adres_bewerken'),
    path('adressen/verwijderen/<slug:slug>/', views.AdresDelete.as_view(), name='adres_verwijderen'),
    # ex /adresboek/adres/4142EA/13
    path('adressen/details/<slug:slug>/', views.AdresDetailView.as_view(), name='adres_details'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from adresboek.admin import adresboek_admin_site

urlpatterns = [
    # Beheer django
    path('systeem/', admin.site.urls),
    # Beheer adresboek
    path('adressen/beheer/', adresboek_admin_site.urls),
    url(r'^', include('adresboek.urls')),
    # Accounts
    url(r'^', include('accounts.urls')),
    # Static Pages
    url(r'^missie', TemplateView.as_view(template_name='pages/missie.html'), name='missie'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Ambon-Diaspora Beheersysteem'
admin.site.site_title = 'Ambon-Diaspora Beheersysteem'
admin.site.index_title = 'Welkom Ambon-Diaspora in het Beheersysteem'

app/adresboek/models.py
from django.conf import settings
from django.db import models
from django.utils.safestring import mark_safe

import uuid


# Create your models here.
class Adres(models.Model):
    class Meta:
        verbose_name_plural = 'Adressen'
        ordering = ['-compleet', 'postcode', 'huisnummer']

    PROVINCIES = (
        ('DR', 'Drenthe'),
        ('FL', 'Flevoland'),
        ('FR', 'Friesland'),
        ('GE', 'Gelderland'),
        ('GR', 'Groningen'),
        ('LI', 'Limburg'),
        ('NB', 'Noord-Brabant'),
        ('NH', 'Noord-Holland'),
        ('OV', 'Overijssel'),
        ('UT', 'Utrecht'),
        ('ZE', 'Zeeland'),
        ('ZH', 'Zuid-Holland'),
    )

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        unique=True,
    )
    slug = models.CharField(
        max_length=36,
        unique=True,
        default=uuid.uuid4,
    )
    vernomen_adres = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )
    straatnaam = models.CharField(
        max_length=100,
        blank=True,
    )
    huisnummer = models.PositiveSmallIntegerField(default=0)
    toevoeging = models.CharField(
        max_length=6,
        blank=True,
        default='',
    )
    postcode = models.CharField(
        max_length=6,
        blank=True,
        help_text='Formaat: 0000AA',
    )
    plaatsnaam = models.CharField(
        max_length=100,
        blank=True,
    )
    deelgemeente = models.CharField(
        max_length=100,
        blank=True,
    )
    provincie = models.CharField(
        max_length=2,
        choices=PROVINCIES,
        blank=True,
    )
    vernomen_bewoners = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )
    in_de_wijk = models.NullBooleanField()
    #debug
    compleet = models.BooleanField(default=0)

    # google_maps_image = models.ImageField(
    #     blank=True,
    #     upload_to='images/external_api_cache/google_maps/',
    #     default='',
    # )
    # google_streetview_image = models.ImageField(
    #     blank=True,
    #     upload_to='images/external_api_cache/google_streetview/',
    #     default='',
    # )
    wijzigings_datum = models.DateField('Laatst gewijzigd', auto_now=True)

    def bewoners(self):
        if self.vernomen_bewoners is '':
            return 'Bewoners Onbekend'
        else:
            return self.vernomen_bewoners

    def bewoond(self):
        if self.bewoners is 'Bewoners Onbekend':
            return False
        else:
            return True

    def volledig_adres(self):
        if self.compleet:
            volledig_adres = '%s %s%s, %s %s' % (
                self.straatnaam,
                self.huisnummer,
                self.toevoeging,
                self.postcode,
                self.plaatsnaam,
            )
        elif self.vernomen_adres:
            volledig_adres = self.vernomen_adres + ', Leerdam'
        else:
            volledig_adres = 'Adres Onbekend'
        return volledig_adres

    def adres_urlformat(self):
        return self.volledig_adres().replace(' ', '%20')

    def get_static_url(self):
        if self.locatie_foto:
            return self.locatie_foto.url
        else:
            return 'images/placeholders/128x128.png'

    def google_streetview_image_url(self):
        return 'https://maps.googleapis.com/maps/api/streetview?size=640x320&location=%s&key=%s' % (
            self.adres_urlformat(),
            settings.GOOGLE_STREETVIEW_IMAGE_KEY,
        )

    def google_maps_image_url(self):
        return 'https://maps.googleapis.com/maps/api/staticmap?center=%s&zoom=17&size=640x320&scale=2&markers=color:green|%s&maptype=hybrid&key=%s' % (
            self.adres_urlformat(),
            self.adres_urlformat(),
            settings.GOOGLE_MAPS_IMAGE_KEY,
        )

    def google_streetview_image_html(self):
        return mark_safe(
            '<img id="streetview-image" src="{url}" width="640" height="320" class="lazyload" />'.format(
                url=self.google_streetview_image_url()
            )
        )

    def google_maps_image_html(self):
        return mark_safe(
            '<img id="static-map-image" src="{url}" width="640" height="320" class="lazyload" />'.format(
                url=self.google_maps_image_url()
            )
        )

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('adresboek:adres_details', args=[str(self.slug)])

    def save(self, *args, **kwargs):
        # Check compleet on Save and change appropriately
        if self.postcode == '0000AA' or self.huisnummer is 0:
            self.compleet = False
        elif self.postcode is not '0000AA':
            self.compleet = True

        # Create UUID for UUID-les Incomplete Adresses
        if len(str(self.slug)) <= 5 and self.compleet is False:
            self.slug = str(uuid.uuid4())
        # Create Address Slug and Images for Complete Adresses
        elif self.compleet is True:
            # Create Slug
            slug = '%s%s%s' % (
                self.postcode,
                self.huisnummer,
                self.toevoeging,
            )
            self.slug = slug.replace('None', '')
        super(Adres, self).save(*args, **kwargs)

    def __str__(self):
        return self.volledig_adres()

app/adresboek/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic

from .models import Adres


# Create your views here.
class AdresListView(LoginRequiredMixin, generic.ListView):
    model = Adres
    template_name = 'adresboek/adres_lijst.html'


class AdresDetailView(LoginRequiredMixin, generic.DetailView):
    model = Adres
    template_name = 'adresboek/adres_details.html'


class AdresCreate(CreateView):
    model = Adres
    fields = [
        'vernomen_bewoners',
        'vernomen_adres',
        'huisnummer',
        'toevoeging',
        'postcode',
    ]


class AdresUpdate(UpdateView):
    model = Adres
    fields = [
        'vernomen_bewoners',
        'vernomen_adres',
        'huisnummer',
        'toevoeging',
        'postcode',
    ]


class AdresDelete(DeleteView):
    model = Adres
    success_url = reverse_lazy('adresboek:adres_lijst')

app/adresboek/templates/adresboek/adres_confirm_delete.html
{% extends 'layout/base_generic.html' %}
  {% block bodyclasses %} adres-details is-scrollable-app has-navbar-fixed-top{% endblock %}

    {% block 'navbar-title' %}
      Adres Verwijderen
    {% endblock %}

    {% block 'navbar-end' %}
      {% include 'partials/header_nav_user_menu.html' %}
    {% endblock %}

      {% block content %}
      <!-- Adres Detail view -->
      <section class="detail-view is-scrollable">
        {% block notifications %}
        {% endblock %}
        {% include 'adresboek/partials/adres_details_tabs.html' %}
        <div id="beheer-knoppen" class="section">
          <p>Weet u zeker dat u dit adres permanent wilt verwijderen? Dit is bamelijk niet meer ongedaan te maken.</p>
          <div class="buttons is-right">
            <form action="" method="POST">
              {% csrf_token %}
              <button class="button is-danger is-outlined">
                <span class="icon"><i class="fas fa-trash" aria-hidden="true"></i></span>
                <span>Verwijderen</span>
              </button>
              <a class="button is-info" href="{% url 'adresboek:adres_details' adres.slug %}">
                <span class="icon"><i class="fas fa-ban" aria-hidden="true"></i></span>
                <span>annuleren</span>
              </a>
            </form>
          </div>
        </div>
      </section>
      {% endblock %}

    {% block footer-scripts %}
    {{ block.super }}
    {% include 'adresboek/scripts_adres_detail.html' %}
    {% endblock %}

app/adresboek/templates/adresboek/adres_details.html
{% extends 'layout/base_generic.html' %}
  {% block bodyclasses %} adresdetails is-scrollable-app has-navbar-fixed-top{% endblock %}

    {% block 'navbar-icon' %}<i class="fas fa-address-card fa-angle-left" aria-hidden="true"></i>{% endblock %}

    {% block 'navbar-title' %}
      Adresdetails
    {% endblock %}

    {% block 'navbar-end' %}
      {% include 'partials/header_nav_user_menu.html' %}
    {% endblock %}

      {% block content %}
      <!-- Adres Detail view -->
      <section class="detail-view is-scrollable">
        {% block notifications %}
        {% endblock %}
        {% include 'adresboek/partials/adres_details_tabs.html' %}
        <div id="beheer-knoppen" class="section">
          <div class="buttons is-right">
            <a class="button is-primary is-outlined" href="{% url 'adresboek:adres_bewerken' adres.slug %}">
              <span class="icon"><i class="fas fa-edit" aria-hidden="true"></i></span>
              <span>Bewerken</span>
            </a>
          </div>
        </div>
        <!-- Contact Details -->
        <section class="contact-details">
          <!--div class="level">
            <div class="level-item has-text-centered">
              <div>
                <p class="header"><span class="icon"><i class="fas fa-phone" aria-hidden="true"></i></span> Telefoon</p>
                <a href=""><span class="placeholder">+31 (0) 6 123 456 78</span></a>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="header"><span class="icon"><i class="fas fa-at" aria-hidden="true"></i></span> Email</p>
                <a href="mailto:"><span class="placeholder">Nyong@Ambon.me</span></a>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="header"><span class="icon"><i class="fab fa-twitter" aria-hidden="true"></i></span> Twitter</p>
                <a href="https://twitter.com"><span class="placeholder">@NyongAmbon</span></a>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="header"><span class="icon"><i class="fab fa-facebook" aria-hidden="true"></i></span> Twitter</p>
                <a href="https://facebook.com"><span class="placeholder">/NyongAmbon</span></a>
              </div>
            </div>
          </div>
          <div class="field is-grouped is-pulled-right">
            <p class="control">
              <a href="" class="button is-success"><span class="icon"><i class="fas fa-question" aria-hidden="true"></i></span> <span>Verzoek Contactgegevens</span></a>
              <a href="" class="button is-danger" disabled><span class="icon"><i class="fas fa-address-card" aria-hidden="true"></i></span> <span>Contactgegevens opslaan</span></a>
            </p>
          </div>
        </section-->
      </section>
      {% endblock %}

    {% block footer-scripts %}
    {{ block.super }}
    {% include 'adresboek/scripts_adres_detail.html' %}
    {% endblock %}

app/adresboek/templates/adresboek/adres_form.html
{% extends 'layout/base_generic.html' %}
  {% block bodyclasses %} adresform is-scrollable-app has-navbar-fixed-top{% endblock %}

    {% block 'navbar-icon' %}<i class="fas fa-address-book fa-angle-left" aria-hidden="true"></i>{% endblock %}

    {% block 'navbar-title' %}
      {% if object is None %}
      Adres Toevoegen
      {% else %}
      Adres Bewerken
      {% endif %}
    {% endblock %}

    {% block 'navbar-end' %}
      {% include 'partials/header_nav_user_menu.html' %}
    {% endblock %}

      {% block content %}
      <!-- Adres Detail view -->
      <section class="detail-view is-scrollable">
        {% block notifications %}
        {% endblock %}
        {% include 'adresboek/partials/adres_details_tabs.html' %}

        <!-- Adres Details -->
        <form action="" method="post">
          <section id="address" class="section">
            {% include 'forms/form_generic.html' %}
          </section>
          <section id="beheer-buttons" class="section">
            <div class="buttons is-right">
          {% if object is None %}
              <a class="button is-info is-outlined" href="{% url 'adresboek:adres_lijst'%}">
                <span class="icon"><i class="fas fa-ban" aria-hidden="true"></i></span>
                <span>Annuleren</span>
              </a>
          {% else %}
              <a class="button is-danger is-outlined" href="{% url 'adresboek:adres_verwijderen' adres.slug %}">
                <span class="icon"><i class="fas fa-trash" aria-hidden="true"></i></span>
                <span>Verwijderen</span>
              </a>
              <a class="button is-info is-outlined" href="{% url 'adresboek:adres_details' adres.slug %}">
                <span class="icon"><i class="fas fa-ban" aria-hidden="true"></i></span>
                <span>Annuleren</span>
              </a>
          {% endif %}
              <button class="button is-primary">
                <span class="icon"><i class="fas fa-edit" aria-hidden="true"></i></span>
                <span>Opslaan</span>
              </button>
            </div>
          </section>
        </form>
        {% endblock %}
      </section>

{% block footer-scripts %}
  {{ block.super }}
  {% include 'adresboek/scripts_adres_detail.html' %}
{% endblock %}

app/adresboek/templates/adresboek/adres_lijst.html
{% extends 'layout/base_generic.html' %}
  {% block bodyclasses %} adreslijst is-scrollable-app has-navbar-fixed-top{% endblock %}

    {% block 'navbar-title' %}
      Adresboek
    {% endblock %}

    {% block 'header-nav' %}
      {% include 'adresboek/header_nav_user_menu.html' with title='Adresboek' %}
    {% endblock %}

      {% block content %}

      <!-- Adres List content -->
      <section id="adres-lijst" class="list-view tile is-parent is-vertical is-scrollable">
        <!-- Search -->
        <div class="adres search tile notification is-danger is-radiusless">
          <div class="field">
            <p class="control has-icons-left has-icons-right is-expanded">
              <input id="zoek-adres-lijst" class="input is-small is-warning is-rounded" type="text" placeholder="Zoek in Adresboek...">
              <span class="icon is-small is-left">
                <i class="fas fa-address-book" aria-hidden="true"></i>
              </span>
              <span class="icon is-small is-right is-">
                <i class="fas fa-search" aria-hidden="true"></i>
              </span>
            </p>
            <p class="help has-text-centered">
              <div class="tags has-addons">
                <span class="tag is-danger">
                Sorteer
                </span>
                <span class="tag is-white sort" data-sort="bewoners">
                bewoners
                </span>
                <span class="tag is-white sort" data-sort="straat">
                straat
                </span>
                <span class="tag is-white sort" data-sort="postcode">
                postcode
                </span>
              </div>
<!--               <span class="tag is-white sort" data-sort="plaatsnaam">
              plaatsnaam
              </span> -->
            </p>
          </div>
        </div>

        <ul class="list">
        {% for adres in adres_list %}
          <!-- Article -->
          <li class="adres is-radiusless notification {% if adres.bewoners == 'Bewoners Onbekend' %} is-info{% elif adres.compleet == 0 %} is-warning{% endif %}">
            <div>
            {% include 'adresboek/partials/adres_details_info.html' %}
            </div>
          </li>
          {% endfor %}
        </ul>
        <ul>
          <li class="adres adres-toevoegen is-radiusless notification is-primary">
            <div class="large-media">
            <a href="{% url 'adresboek:adres_toevoegen' %}"></a>
              <figure class="image is-2by1">
                <div class="fa-layers fa-fw fa-5x" style="position: absolute;margin: auto;top: 0;left: 0;right: 0;bottom: 0;">
                  <i class="fas fa-home"></i>
                  <i class="fas fa-plus" data-fa-transform="shrink-7 right-5" style="color:#661626"></i>
                  <i class="fas fa-plus" data-fa-transform="shrink-8 right-5"></i>
                </div>
              </figure>
              <div class="content">
                <p>
                  <span class="bewoners is-size-5">Adres Toevoegen</span>
                </p>
              </div>
            </div>
          </li>
        </ul>
      </section>
      {% endblock %}

    {% block footer-scripts %}
    {{ block.super }}
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    <script>
      var options = {
        valueNames: [ 'bewoners', 'onvolledig', 'straat', 'postcode', 'plaatsnaam' ],
      };

      var adreslijst = new List('adres-lijst', options);
      $('#zoek-adres-lijst').on('keyup', function() {
        var searchString = $(this).val();
        adreslijst.search(searchString);
      });
    </script>
    {% endblock %}

app/adresboek/templates/adresboek/scripts_adres_detail.html
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-6mQUEWW8VQ-9GSkDwS9JM_uogtRNls8&callback=initialize&language=nl&region=NL">
    </script>
    <script>
      var geocoder;
      var map;
      var panorama;

      function initialize() {
        var mapElement = document.getElementById('map'),
        panoElement = document.getElementById('pano'),
        adres = "{{ adres.volledig_adres }}",
        geolocatie = {lat: {{ adres.postcode.breedtegraad }}, lng: {{ adres.postcode.lengtegraad }} };
        geocoder = new google.maps.Geocoder()
        geocoder.geocode( { 'address': adres }, function(results, status) {
          if (status == 'OK') {
            geolocatie = results[0].geometry.location;
          } else {
            document.getElementById('google-result').innerHTML = 'Kon het adres niet opzoeken want: ' + status;
          }
        });

        var mapOptions = {
          zoom: 17,
          center: geolocatie,
          mapTypeId: 'hybrid',
        }

        var panoOptions = {
          position: geolocatie,
          motionTracking: false,
        }

        map = new google.maps.Map(mapElement, mapOptions);
        panorama = new google.maps.StreetViewPanorama(panoElement, panoOptions);

        map.setStreetView(panorama);
      }

      function codeAddress() {
        var zoek_adres = document.getElementById('id_vernomen_adres').value + ',Leerdam';
        geocoder.geocode( { 'address': zoek_adres}, function(results, status) {
          if (status == 'OK') {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
            // Display Adress
            document.getElementById('google-result').innerHTML = '<p>Adres: ' + results[0].formatted_address + '</p>';
            // Update Picture
            document.getElementById('streetview-image').src = 'https://maps.googleapis.com/maps/api/streetview?size=640x320&location=' + encodeURIComponent(results[0].formatted_address) + '&key=AIzaSyA-6mQUEWW8VQ-9GSkDwS9JM_uogtRNls8';
            for (var i = 0; i < results[0].address_components.length; i++) {
              var address_components = results[0].address_components[i];
              if (address_components.types[0] == 'postal_code') {
                console.log('postcode: ' + address_components.long_name);
              }
              if (address_components.types[0] == 'street_number') {
                console.log('huisnummer: ' + address_components.long_name);
              }
            }

          } else {
            document.getElementById('google-result').innerHTML = 'Kon het adres niet opzoeken want: ' + status;
          }
        });
      }
    </script>